/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 105
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__key_segment = 1,
  sym__newline = 2,
  anon_sym_POUND = 3,
  aux_sym_comment_token1 = 4,
  sym_sep_raw = 5,
  sym_sep_int = 6,
  sym_sep_float = 7,
  sym_sep_string = 8,
  anon_sym_DOT = 9,
  anon_sym_LBRACE_RBRACE = 10,
  anon_sym_LBRACK_RBRACK = 11,
  anon_sym_LPAREN_RPAREN = 12,
  anon_sym_LPAREN_LPAREN_RPAREN_RPAREN = 13,
  sym_open_brace = 14,
  anon_sym_RBRACE = 15,
  sym_open_bracket = 16,
  anon_sym_RBRACK = 17,
  sym_open_paren = 18,
  sym_open_dparen = 19,
  sym_multiline_content_line = 20,
  sym__scalar_text = 21,
  sym_kw_null = 22,
  sym_kw_true = 23,
  sym_kw_false = 24,
  sym__marker_ws = 25,
  sym__strict_eol = 26,
  sym__stripped_close = 27,
  sym__verbatim_close = 28,
  sym_source_file = 29,
  sym__line = 30,
  sym_blank_line = 31,
  sym_comment = 32,
  sym_object_pair = 33,
  sym_key = 34,
  sym_dotted_key = 35,
  sym__value_line = 36,
  sym_empty_value = 37,
  sym_empty_object = 38,
  sym_empty_array = 39,
  sym_empty_paren = 40,
  sym_empty_double_paren = 41,
  sym_close_brace = 42,
  sym_close_bracket = 43,
  sym_close_paren = 44,
  sym_close_dparen = 45,
  sym_compound_object = 46,
  sym_compound_array = 47,
  sym_array_item = 48,
  sym_multiline_stripped = 49,
  sym_multiline_verbatim = 50,
  sym_scalar = 51,
  sym_keyword = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_dotted_key_repeat1 = 54,
  aux_sym_compound_object_repeat1 = 55,
  aux_sym_compound_array_repeat1 = 56,
  aux_sym_multiline_stripped_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__key_segment] = "_key_segment",
  [sym__newline] = "_newline",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_sep_raw] = "sep_raw",
  [sym_sep_int] = "sep_int",
  [sym_sep_float] = "sep_float",
  [sym_sep_string] = "sep_string",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LPAREN_RPAREN] = "()",
  [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = "(())",
  [sym_open_brace] = "open_brace",
  [anon_sym_RBRACE] = "}",
  [sym_open_bracket] = "open_bracket",
  [anon_sym_RBRACK] = "]",
  [sym_open_paren] = "open_paren",
  [sym_open_dparen] = "open_dparen",
  [sym_multiline_content_line] = "multiline_content_line",
  [sym__scalar_text] = "_scalar_text",
  [sym_kw_null] = "kw_null",
  [sym_kw_true] = "kw_true",
  [sym_kw_false] = "kw_false",
  [sym__marker_ws] = "_marker_ws",
  [sym__strict_eol] = "_strict_eol",
  [sym__stripped_close] = "_stripped_close",
  [sym__verbatim_close] = "_verbatim_close",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [sym_object_pair] = "object_pair",
  [sym_key] = "key",
  [sym_dotted_key] = "dotted_key",
  [sym__value_line] = "_value_line",
  [sym_empty_value] = "empty_value",
  [sym_empty_object] = "empty_object",
  [sym_empty_array] = "empty_array",
  [sym_empty_paren] = "empty_paren",
  [sym_empty_double_paren] = "empty_double_paren",
  [sym_close_brace] = "close_brace",
  [sym_close_bracket] = "close_bracket",
  [sym_close_paren] = "close_paren",
  [sym_close_dparen] = "close_dparen",
  [sym_compound_object] = "compound_object",
  [sym_compound_array] = "compound_array",
  [sym_array_item] = "array_item",
  [sym_multiline_stripped] = "multiline_stripped",
  [sym_multiline_verbatim] = "multiline_verbatim",
  [sym_scalar] = "scalar",
  [sym_keyword] = "keyword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_dotted_key_repeat1] = "dotted_key_repeat1",
  [aux_sym_compound_object_repeat1] = "compound_object_repeat1",
  [aux_sym_compound_array_repeat1] = "compound_array_repeat1",
  [aux_sym_multiline_stripped_repeat1] = "multiline_stripped_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__key_segment] = sym__key_segment,
  [sym__newline] = sym__newline,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_sep_raw] = sym_sep_raw,
  [sym_sep_int] = sym_sep_int,
  [sym_sep_float] = sym_sep_float,
  [sym_sep_string] = sym_sep_string,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
  [sym_open_brace] = sym_open_brace,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_open_bracket] = sym_open_bracket,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_open_paren] = sym_open_paren,
  [sym_open_dparen] = sym_open_dparen,
  [sym_multiline_content_line] = sym_multiline_content_line,
  [sym__scalar_text] = sym__scalar_text,
  [sym_kw_null] = sym_kw_null,
  [sym_kw_true] = sym_kw_true,
  [sym_kw_false] = sym_kw_false,
  [sym__marker_ws] = sym__marker_ws,
  [sym__strict_eol] = sym__strict_eol,
  [sym__stripped_close] = sym__stripped_close,
  [sym__verbatim_close] = sym__verbatim_close,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [sym_object_pair] = sym_object_pair,
  [sym_key] = sym_key,
  [sym_dotted_key] = sym_dotted_key,
  [sym__value_line] = sym__value_line,
  [sym_empty_value] = sym_empty_value,
  [sym_empty_object] = sym_empty_object,
  [sym_empty_array] = sym_empty_array,
  [sym_empty_paren] = sym_empty_paren,
  [sym_empty_double_paren] = sym_empty_double_paren,
  [sym_close_brace] = sym_close_brace,
  [sym_close_bracket] = sym_close_bracket,
  [sym_close_paren] = sym_close_paren,
  [sym_close_dparen] = sym_close_dparen,
  [sym_compound_object] = sym_compound_object,
  [sym_compound_array] = sym_compound_array,
  [sym_array_item] = sym_array_item,
  [sym_multiline_stripped] = sym_multiline_stripped,
  [sym_multiline_verbatim] = sym_multiline_verbatim,
  [sym_scalar] = sym_scalar,
  [sym_keyword] = sym_keyword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_dotted_key_repeat1] = aux_sym_dotted_key_repeat1,
  [aux_sym_compound_object_repeat1] = aux_sym_compound_object_repeat1,
  [aux_sym_compound_array_repeat1] = aux_sym_compound_array_repeat1,
  [aux_sym_multiline_stripped_repeat1] = aux_sym_multiline_stripped_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__key_segment] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_sep_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_sep_int] = {
    .visible = true,
    .named = true,
  },
  [sym_sep_float] = {
    .visible = true,
    .named = true,
  },
  [sym_sep_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_open_brace] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_open_bracket] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_open_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_open_dparen] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar_text] = {
    .visible = false,
    .named = true,
  },
  [sym_kw_null] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_true] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_false] = {
    .visible = true,
    .named = true,
  },
  [sym__marker_ws] = {
    .visible = false,
    .named = true,
  },
  [sym__strict_eol] = {
    .visible = false,
    .named = true,
  },
  [sym__stripped_close] = {
    .visible = false,
    .named = true,
  },
  [sym__verbatim_close] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_object_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_key] = {
    .visible = true,
    .named = true,
  },
  [sym__value_line] = {
    .visible = false,
    .named = true,
  },
  [sym_empty_value] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_object] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_array] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_double_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_close_brace] = {
    .visible = true,
    .named = true,
  },
  [sym_close_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_close_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_close_dparen] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_object] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_item] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_stripped] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_key_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_stripped_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_marker = 2,
  field_separator = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_marker] = "marker",
  [field_separator] = "separator",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_separator, 1},
    {field_value, 3},
  [3] =
    {field_value, 0},
  [4] =
    {field_marker, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 34,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 25,
  [43] = 11,
  [44] = 21,
  [45] = 22,
  [46] = 23,
  [47] = 24,
  [48] = 26,
  [49] = 27,
  [50] = 28,
  [51] = 8,
  [52] = 29,
  [53] = 30,
  [54] = 13,
  [55] = 55,
  [56] = 14,
  [57] = 57,
  [58] = 12,
  [59] = 15,
  [60] = 16,
  [61] = 17,
  [62] = 18,
  [63] = 19,
  [64] = 31,
  [65] = 20,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 67,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 68,
  [76] = 69,
  [77] = 66,
  [78] = 78,
  [79] = 78,
  [80] = 80,
  [81] = 80,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 86,
  [92] = 82,
  [93] = 93,
  [94] = 94,
  [95] = 83,
  [96] = 93,
  [97] = 90,
  [98] = 98,
  [99] = 94,
  [100] = 98,
  [101] = 88,
  [102] = 102,
  [103] = 103,
  [104] = 103,
};

static const TSCharacterRange sym__key_segment_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '-'}, {'/', '9'}, {';', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '#', 20,
        '(', 29,
        '.', 28,
        ':', 27,
        '[', 7,
        ']', 50,
        'f', 32,
        'n', 41,
        't', 38,
        '{', 10,
        '}', 48,
        '\t', 2,
        ' ', 2,
        0x0b, 14,
        '\f', 14,
      );
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(19);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '#', 20,
        '(', 29,
        '.', 28,
        ':', 27,
        '[', 7,
        ']', 50,
        'f', 32,
        'n', 41,
        't', 38,
        '{', 10,
        '}', 48,
        '\t', 2,
        ' ', 2,
        0x0b, 14,
        '\f', 14,
      );
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '#', 21,
        '(', 58,
        ':', 63,
        '[', 54,
        ']', 50,
        'f', 64,
        'n', 73,
        't', 70,
        '{', 56,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(74);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 19,
        '\r', 1,
        '(', 58,
        '[', 54,
        'f', 64,
        'n', 73,
        't', 70,
        '{', 56,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(74);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(74);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ']') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(47);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead == '\r') ADVANCE(12);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '\n') ADVANCE(51);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(52);
      END_STATE();
    case 17:
      if (eof) ADVANCE(18);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '.') ADVANCE(28);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '}') ADVANCE(48);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(17);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(42);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_sep_raw);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_sep_int);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_sep_float);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_sep_string);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(45);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == ')') ADVANCE(46);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == ')') ADVANCE(30);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'a') ADVANCE(35);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'e') ADVANCE(76);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'e') ADVANCE(77);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'l') ADVANCE(39);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'l') ADVANCE(75);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'l') ADVANCE(36);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'r') ADVANCE(40);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 's') ADVANCE(34);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'u') ADVANCE(33);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'u') ADVANCE(37);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__key_segment);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LPAREN_LPAREN_RPAREN_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_open_brace);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_open_bracket);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_open_paren);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_open_dparen);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_multiline_content_line);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ']') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(49);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(15);
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == ')') ADVANCE(45);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\r') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\r') ADVANCE(16);
      if (lookahead == ')') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(52);
      if (lookahead == '\r') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(74);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'a') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'l') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'l') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'l') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'r') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'u') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'u') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_kw_null);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_kw_true);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_kw_false);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 17},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 17},
  [33] = {.lex_state = 17},
  [34] = {.lex_state = 17},
  [35] = {.lex_state = 17},
  [36] = {.lex_state = 17},
  [37] = {.lex_state = 17},
  [38] = {.lex_state = 17},
  [39] = {.lex_state = 17},
  [40] = {.lex_state = 17},
  [41] = {.lex_state = 17},
  [42] = {.lex_state = 17},
  [43] = {.lex_state = 17},
  [44] = {.lex_state = 17},
  [45] = {.lex_state = 17},
  [46] = {.lex_state = 17},
  [47] = {.lex_state = 17},
  [48] = {.lex_state = 17},
  [49] = {.lex_state = 17},
  [50] = {.lex_state = 17},
  [51] = {.lex_state = 17},
  [52] = {.lex_state = 17},
  [53] = {.lex_state = 17},
  [54] = {.lex_state = 17},
  [55] = {.lex_state = 17},
  [56] = {.lex_state = 17},
  [57] = {.lex_state = 17},
  [58] = {.lex_state = 17},
  [59] = {.lex_state = 17},
  [60] = {.lex_state = 17},
  [61] = {.lex_state = 17},
  [62] = {.lex_state = 17},
  [63] = {.lex_state = 17},
  [64] = {.lex_state = 17},
  [65] = {.lex_state = 17},
  [66] = {.lex_state = 13, .external_lex_state = 2},
  [67] = {.lex_state = 13, .external_lex_state = 2},
  [68] = {.lex_state = 13, .external_lex_state = 3},
  [69] = {.lex_state = 13, .external_lex_state = 3},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 13, .external_lex_state = 2},
  [72] = {.lex_state = 17},
  [73] = {.lex_state = 17},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 13, .external_lex_state = 3},
  [76] = {.lex_state = 13, .external_lex_state = 3},
  [77] = {.lex_state = 13, .external_lex_state = 2},
  [78] = {.lex_state = 13, .external_lex_state = 2},
  [79] = {.lex_state = 13, .external_lex_state = 3},
  [80] = {.lex_state = 22},
  [81] = {.lex_state = 22},
  [82] = {.lex_state = 17},
  [83] = {.lex_state = 17},
  [84] = {.lex_state = 0, .external_lex_state = 4},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 17},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 0, .external_lex_state = 5},
  [89] = {.lex_state = 17},
  [90] = {.lex_state = 17},
  [91] = {.lex_state = 17},
  [92] = {.lex_state = 17},
  [93] = {.lex_state = 17},
  [94] = {.lex_state = 17},
  [95] = {.lex_state = 17},
  [96] = {.lex_state = 17},
  [97] = {.lex_state = 17},
  [98] = {.lex_state = 17},
  [99] = {.lex_state = 17},
  [100] = {.lex_state = 17},
  [101] = {.lex_state = 0, .external_lex_state = 5},
  [102] = {.lex_state = 0, .external_lex_state = 4},
  [103] = {.lex_state = 0, .external_lex_state = 5},
  [104] = {.lex_state = 0, .external_lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__key_segment] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_sep_raw] = ACTIONS(1),
    [sym_sep_int] = ACTIONS(1),
    [sym_sep_float] = ACTIONS(1),
    [sym_sep_string] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(1),
    [sym_open_brace] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_open_bracket] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_multiline_content_line] = ACTIONS(1),
    [sym_kw_null] = ACTIONS(1),
    [sym_kw_true] = ACTIONS(1),
    [sym_kw_false] = ACTIONS(1),
    [sym__marker_ws] = ACTIONS(1),
    [sym__strict_eol] = ACTIONS(1),
    [sym__stripped_close] = ACTIONS(1),
    [sym__verbatim_close] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(85),
    [sym__line] = STATE(32),
    [sym_blank_line] = STATE(32),
    [sym_comment] = STATE(32),
    [sym_object_pair] = STATE(32),
    [sym_key] = STATE(73),
    [sym_dotted_key] = STATE(72),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__key_segment] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_blank_line] = STATE(6),
    [sym_comment] = STATE(6),
    [sym__value_line] = STATE(9),
    [sym_empty_object] = STATE(9),
    [sym_empty_array] = STATE(9),
    [sym_empty_paren] = STATE(9),
    [sym_empty_double_paren] = STATE(9),
    [sym_close_bracket] = STATE(8),
    [sym_compound_object] = STATE(9),
    [sym_compound_array] = STATE(9),
    [sym_array_item] = STATE(6),
    [sym_multiline_stripped] = STATE(9),
    [sym_multiline_verbatim] = STATE(9),
    [sym_scalar] = STATE(9),
    [sym_keyword] = STATE(9),
    [aux_sym_compound_array_repeat1] = STATE(6),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym_open_brace] = ACTIONS(25),
    [sym_open_bracket] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(29),
    [sym_open_paren] = ACTIONS(31),
    [sym_open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
  [STATE(3)] = {
    [sym_blank_line] = STATE(4),
    [sym_comment] = STATE(4),
    [sym__value_line] = STATE(9),
    [sym_empty_object] = STATE(9),
    [sym_empty_array] = STATE(9),
    [sym_empty_paren] = STATE(9),
    [sym_empty_double_paren] = STATE(9),
    [sym_close_bracket] = STATE(65),
    [sym_compound_object] = STATE(9),
    [sym_compound_array] = STATE(9),
    [sym_array_item] = STATE(4),
    [sym_multiline_stripped] = STATE(9),
    [sym_multiline_verbatim] = STATE(9),
    [sym_scalar] = STATE(9),
    [sym_keyword] = STATE(9),
    [aux_sym_compound_array_repeat1] = STATE(4),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym_open_brace] = ACTIONS(25),
    [sym_open_bracket] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_open_paren] = ACTIONS(31),
    [sym_open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym_blank_line] = STATE(6),
    [sym_comment] = STATE(6),
    [sym__value_line] = STATE(9),
    [sym_empty_object] = STATE(9),
    [sym_empty_array] = STATE(9),
    [sym_empty_paren] = STATE(9),
    [sym_empty_double_paren] = STATE(9),
    [sym_close_bracket] = STATE(51),
    [sym_compound_object] = STATE(9),
    [sym_compound_array] = STATE(9),
    [sym_array_item] = STATE(6),
    [sym_multiline_stripped] = STATE(9),
    [sym_multiline_verbatim] = STATE(9),
    [sym_scalar] = STATE(9),
    [sym_keyword] = STATE(9),
    [aux_sym_compound_array_repeat1] = STATE(6),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym_open_brace] = ACTIONS(25),
    [sym_open_bracket] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(39),
    [sym_open_paren] = ACTIONS(31),
    [sym_open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
  [STATE(5)] = {
    [sym_blank_line] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__value_line] = STATE(9),
    [sym_empty_object] = STATE(9),
    [sym_empty_array] = STATE(9),
    [sym_empty_paren] = STATE(9),
    [sym_empty_double_paren] = STATE(9),
    [sym_close_bracket] = STATE(20),
    [sym_compound_object] = STATE(9),
    [sym_compound_array] = STATE(9),
    [sym_array_item] = STATE(2),
    [sym_multiline_stripped] = STATE(9),
    [sym_multiline_verbatim] = STATE(9),
    [sym_scalar] = STATE(9),
    [sym_keyword] = STATE(9),
    [aux_sym_compound_array_repeat1] = STATE(2),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym_open_brace] = ACTIONS(25),
    [sym_open_bracket] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(29),
    [sym_open_paren] = ACTIONS(31),
    [sym_open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
  [STATE(6)] = {
    [sym_blank_line] = STATE(6),
    [sym_comment] = STATE(6),
    [sym__value_line] = STATE(9),
    [sym_empty_object] = STATE(9),
    [sym_empty_array] = STATE(9),
    [sym_empty_paren] = STATE(9),
    [sym_empty_double_paren] = STATE(9),
    [sym_compound_object] = STATE(9),
    [sym_compound_array] = STATE(9),
    [sym_array_item] = STATE(6),
    [sym_multiline_stripped] = STATE(9),
    [sym_multiline_verbatim] = STATE(9),
    [sym_scalar] = STATE(9),
    [sym_keyword] = STATE(9),
    [aux_sym_compound_array_repeat1] = STATE(6),
    [sym__newline] = ACTIONS(41),
    [anon_sym_POUND] = ACTIONS(44),
    [sym_sep_raw] = ACTIONS(47),
    [sym_sep_int] = ACTIONS(47),
    [sym_sep_float] = ACTIONS(47),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(50),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(53),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(56),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(59),
    [sym_open_brace] = ACTIONS(62),
    [sym_open_bracket] = ACTIONS(65),
    [anon_sym_RBRACK] = ACTIONS(68),
    [sym_open_paren] = ACTIONS(70),
    [sym_open_dparen] = ACTIONS(73),
    [sym__scalar_text] = ACTIONS(76),
    [sym_kw_null] = ACTIONS(79),
    [sym_kw_true] = ACTIONS(79),
    [sym_kw_false] = ACTIONS(79),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(82), 1,
      sym__newline,
    ACTIONS(84), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(86), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(88), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(90), 1,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
    ACTIONS(92), 1,
      sym_open_brace,
    ACTIONS(94), 1,
      sym_open_bracket,
    ACTIONS(96), 1,
      sym_open_paren,
    ACTIONS(98), 1,
      sym_open_dparen,
    ACTIONS(100), 1,
      sym__scalar_text,
    ACTIONS(102), 3,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
    STATE(57), 12,
      sym__value_line,
      sym_empty_value,
      sym_empty_object,
      sym_empty_array,
      sym_empty_paren,
      sym_empty_double_paren,
      sym_compound_object,
      sym_compound_array,
      sym_multiline_stripped,
      sym_multiline_verbatim,
      sym_scalar,
      sym_keyword,
  [50] = 2,
    ACTIONS(106), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(104), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [73] = 2,
    ACTIONS(110), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(108), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [96] = 2,
    ACTIONS(114), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(112), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [119] = 2,
    ACTIONS(118), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(116), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [142] = 2,
    ACTIONS(122), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(120), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [165] = 2,
    ACTIONS(126), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(124), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [188] = 2,
    ACTIONS(130), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(128), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [211] = 2,
    ACTIONS(134), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(132), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [234] = 2,
    ACTIONS(138), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(136), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [257] = 2,
    ACTIONS(142), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(140), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [280] = 2,
    ACTIONS(146), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(144), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [303] = 2,
    ACTIONS(150), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(148), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [326] = 2,
    ACTIONS(154), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(152), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [349] = 2,
    ACTIONS(158), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(156), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [372] = 2,
    ACTIONS(162), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(160), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [395] = 2,
    ACTIONS(166), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(164), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [418] = 2,
    ACTIONS(170), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(168), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [441] = 2,
    ACTIONS(174), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(172), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [464] = 2,
    ACTIONS(178), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(176), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [487] = 2,
    ACTIONS(182), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(180), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [510] = 2,
    ACTIONS(186), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(184), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [533] = 2,
    ACTIONS(190), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(188), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [556] = 2,
    ACTIONS(194), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(192), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [579] = 2,
    ACTIONS(198), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(196), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym_open_brace,
      sym_open_bracket,
      anon_sym_RBRACK,
      sym_open_paren,
      sym_open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [602] = 7,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      sym_dotted_key,
    STATE(73), 1,
      sym_key,
    STATE(33), 5,
      sym__line,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_source_file_repeat1,
  [628] = 7,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 1,
      sym__key_segment,
    ACTIONS(207), 1,
      sym__newline,
    ACTIONS(210), 1,
      anon_sym_POUND,
    STATE(72), 1,
      sym_dotted_key,
    STATE(73), 1,
      sym_key,
    STATE(33), 5,
      sym__line,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_source_file_repeat1,
  [654] = 8,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(27), 1,
      sym_close_brace,
    STATE(72), 1,
      sym_dotted_key,
    STATE(73), 1,
      sym_key,
    STATE(38), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [682] = 8,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_close_brace,
    STATE(72), 1,
      sym_dotted_key,
    STATE(73), 1,
      sym_key,
    STATE(37), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [710] = 8,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_close_brace,
    STATE(72), 1,
      sym_dotted_key,
    STATE(73), 1,
      sym_key,
    STATE(34), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [738] = 8,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_close_brace,
    STATE(72), 1,
      sym_dotted_key,
    STATE(73), 1,
      sym_key,
    STATE(38), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [766] = 7,
    ACTIONS(217), 1,
      sym__key_segment,
    ACTIONS(220), 1,
      sym__newline,
    ACTIONS(223), 1,
      anon_sym_POUND,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_dotted_key,
    STATE(73), 1,
      sym_key,
    STATE(38), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [791] = 4,
    ACTIONS(230), 1,
      sym_sep_string,
    ACTIONS(232), 1,
      anon_sym_DOT,
    STATE(39), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(228), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [806] = 4,
    ACTIONS(237), 1,
      sym_sep_string,
    ACTIONS(239), 1,
      anon_sym_DOT,
    STATE(39), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(235), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [821] = 4,
    ACTIONS(239), 1,
      anon_sym_DOT,
    ACTIONS(243), 1,
      sym_sep_string,
    STATE(40), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(241), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [836] = 1,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [844] = 1,
    ACTIONS(116), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [852] = 1,
    ACTIONS(156), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [860] = 1,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [868] = 1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [876] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [884] = 1,
    ACTIONS(176), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [892] = 1,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [900] = 1,
    ACTIONS(184), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [908] = 1,
    ACTIONS(104), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [916] = 1,
    ACTIONS(188), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [924] = 1,
    ACTIONS(192), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [932] = 1,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [940] = 2,
    ACTIONS(230), 1,
      sym_sep_string,
    ACTIONS(228), 4,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_DOT,
  [950] = 1,
    ACTIONS(128), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [958] = 1,
    ACTIONS(245), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [966] = 1,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [974] = 1,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [982] = 1,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [990] = 1,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [998] = 1,
    ACTIONS(144), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [1006] = 1,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [1014] = 1,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [1022] = 1,
    ACTIONS(152), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      anon_sym_RBRACE,
  [1030] = 4,
    ACTIONS(247), 1,
      sym_multiline_content_line,
    ACTIONS(249), 1,
      sym__verbatim_close,
    STATE(47), 1,
      sym_close_dparen,
    STATE(67), 1,
      aux_sym_multiline_stripped_repeat1,
  [1043] = 4,
    ACTIONS(249), 1,
      sym__verbatim_close,
    ACTIONS(251), 1,
      sym_multiline_content_line,
    STATE(53), 1,
      sym_close_dparen,
    STATE(78), 1,
      aux_sym_multiline_stripped_repeat1,
  [1056] = 4,
    ACTIONS(253), 1,
      sym_multiline_content_line,
    ACTIONS(255), 1,
      sym__stripped_close,
    STATE(29), 1,
      sym_close_paren,
    STATE(79), 1,
      aux_sym_multiline_stripped_repeat1,
  [1069] = 4,
    ACTIONS(257), 1,
      sym_multiline_content_line,
    ACTIONS(259), 1,
      sym__stripped_close,
    STATE(45), 1,
      sym_close_paren,
    STATE(75), 1,
      aux_sym_multiline_stripped_repeat1,
  [1082] = 3,
    ACTIONS(261), 1,
      sym__newline,
    ACTIONS(263), 1,
      sym__scalar_text,
    STATE(10), 2,
      sym_empty_value,
      sym_scalar,
  [1093] = 4,
    ACTIONS(251), 1,
      sym_multiline_content_line,
    ACTIONS(265), 1,
      sym__verbatim_close,
    STATE(30), 1,
      sym_close_dparen,
    STATE(78), 1,
      aux_sym_multiline_stripped_repeat1,
  [1106] = 2,
    ACTIONS(243), 1,
      sym_sep_string,
    ACTIONS(241), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [1115] = 2,
    ACTIONS(269), 1,
      sym_sep_string,
    ACTIONS(267), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [1124] = 3,
    ACTIONS(82), 1,
      sym__newline,
    ACTIONS(271), 1,
      sym__scalar_text,
    STATE(57), 2,
      sym_empty_value,
      sym_scalar,
  [1135] = 4,
    ACTIONS(253), 1,
      sym_multiline_content_line,
    ACTIONS(259), 1,
      sym__stripped_close,
    STATE(52), 1,
      sym_close_paren,
    STATE(79), 1,
      aux_sym_multiline_stripped_repeat1,
  [1148] = 4,
    ACTIONS(255), 1,
      sym__stripped_close,
    ACTIONS(273), 1,
      sym_multiline_content_line,
    STATE(22), 1,
      sym_close_paren,
    STATE(68), 1,
      aux_sym_multiline_stripped_repeat1,
  [1161] = 4,
    ACTIONS(265), 1,
      sym__verbatim_close,
    ACTIONS(275), 1,
      sym_multiline_content_line,
    STATE(24), 1,
      sym_close_dparen,
    STATE(71), 1,
      aux_sym_multiline_stripped_repeat1,
  [1174] = 3,
    ACTIONS(277), 1,
      sym_multiline_content_line,
    ACTIONS(280), 1,
      sym__verbatim_close,
    STATE(78), 1,
      aux_sym_multiline_stripped_repeat1,
  [1184] = 3,
    ACTIONS(280), 1,
      sym__stripped_close,
    ACTIONS(282), 1,
      sym_multiline_content_line,
    STATE(79), 1,
      aux_sym_multiline_stripped_repeat1,
  [1194] = 2,
    ACTIONS(285), 1,
      sym__newline,
    ACTIONS(287), 1,
      aux_sym_comment_token1,
  [1201] = 2,
    ACTIONS(289), 1,
      sym__newline,
    ACTIONS(291), 1,
      aux_sym_comment_token1,
  [1208] = 1,
    ACTIONS(293), 1,
      sym__newline,
  [1212] = 1,
    ACTIONS(295), 1,
      sym__newline,
  [1216] = 1,
    ACTIONS(297), 1,
      sym__marker_ws,
  [1220] = 1,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
  [1224] = 1,
    ACTIONS(301), 1,
      sym__newline,
  [1228] = 1,
    ACTIONS(303), 1,
      sym__marker_ws,
  [1232] = 1,
    ACTIONS(305), 1,
      sym__strict_eol,
  [1236] = 1,
    ACTIONS(307), 1,
      sym__key_segment,
  [1240] = 1,
    ACTIONS(309), 1,
      sym__newline,
  [1244] = 1,
    ACTIONS(311), 1,
      sym__newline,
  [1248] = 1,
    ACTIONS(313), 1,
      sym__newline,
  [1252] = 1,
    ACTIONS(315), 1,
      sym__newline,
  [1256] = 1,
    ACTIONS(317), 1,
      sym__newline,
  [1260] = 1,
    ACTIONS(319), 1,
      sym__newline,
  [1264] = 1,
    ACTIONS(321), 1,
      sym__newline,
  [1268] = 1,
    ACTIONS(323), 1,
      sym__newline,
  [1272] = 1,
    ACTIONS(325), 1,
      sym__newline,
  [1276] = 1,
    ACTIONS(327), 1,
      sym__newline,
  [1280] = 1,
    ACTIONS(329), 1,
      sym__newline,
  [1284] = 1,
    ACTIONS(331), 1,
      sym__strict_eol,
  [1288] = 1,
    ACTIONS(333), 1,
      sym__marker_ws,
  [1292] = 1,
    ACTIONS(335), 1,
      sym__strict_eol,
  [1296] = 1,
    ACTIONS(337), 1,
      sym__strict_eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 73,
  [SMALL_STATE(10)] = 96,
  [SMALL_STATE(11)] = 119,
  [SMALL_STATE(12)] = 142,
  [SMALL_STATE(13)] = 165,
  [SMALL_STATE(14)] = 188,
  [SMALL_STATE(15)] = 211,
  [SMALL_STATE(16)] = 234,
  [SMALL_STATE(17)] = 257,
  [SMALL_STATE(18)] = 280,
  [SMALL_STATE(19)] = 303,
  [SMALL_STATE(20)] = 326,
  [SMALL_STATE(21)] = 349,
  [SMALL_STATE(22)] = 372,
  [SMALL_STATE(23)] = 395,
  [SMALL_STATE(24)] = 418,
  [SMALL_STATE(25)] = 441,
  [SMALL_STATE(26)] = 464,
  [SMALL_STATE(27)] = 487,
  [SMALL_STATE(28)] = 510,
  [SMALL_STATE(29)] = 533,
  [SMALL_STATE(30)] = 556,
  [SMALL_STATE(31)] = 579,
  [SMALL_STATE(32)] = 602,
  [SMALL_STATE(33)] = 628,
  [SMALL_STATE(34)] = 654,
  [SMALL_STATE(35)] = 682,
  [SMALL_STATE(36)] = 710,
  [SMALL_STATE(37)] = 738,
  [SMALL_STATE(38)] = 766,
  [SMALL_STATE(39)] = 791,
  [SMALL_STATE(40)] = 806,
  [SMALL_STATE(41)] = 821,
  [SMALL_STATE(42)] = 836,
  [SMALL_STATE(43)] = 844,
  [SMALL_STATE(44)] = 852,
  [SMALL_STATE(45)] = 860,
  [SMALL_STATE(46)] = 868,
  [SMALL_STATE(47)] = 876,
  [SMALL_STATE(48)] = 884,
  [SMALL_STATE(49)] = 892,
  [SMALL_STATE(50)] = 900,
  [SMALL_STATE(51)] = 908,
  [SMALL_STATE(52)] = 916,
  [SMALL_STATE(53)] = 924,
  [SMALL_STATE(54)] = 932,
  [SMALL_STATE(55)] = 940,
  [SMALL_STATE(56)] = 950,
  [SMALL_STATE(57)] = 958,
  [SMALL_STATE(58)] = 966,
  [SMALL_STATE(59)] = 974,
  [SMALL_STATE(60)] = 982,
  [SMALL_STATE(61)] = 990,
  [SMALL_STATE(62)] = 998,
  [SMALL_STATE(63)] = 1006,
  [SMALL_STATE(64)] = 1014,
  [SMALL_STATE(65)] = 1022,
  [SMALL_STATE(66)] = 1030,
  [SMALL_STATE(67)] = 1043,
  [SMALL_STATE(68)] = 1056,
  [SMALL_STATE(69)] = 1069,
  [SMALL_STATE(70)] = 1082,
  [SMALL_STATE(71)] = 1093,
  [SMALL_STATE(72)] = 1106,
  [SMALL_STATE(73)] = 1115,
  [SMALL_STATE(74)] = 1124,
  [SMALL_STATE(75)] = 1135,
  [SMALL_STATE(76)] = 1148,
  [SMALL_STATE(77)] = 1161,
  [SMALL_STATE(78)] = 1174,
  [SMALL_STATE(79)] = 1184,
  [SMALL_STATE(80)] = 1194,
  [SMALL_STATE(81)] = 1201,
  [SMALL_STATE(82)] = 1208,
  [SMALL_STATE(83)] = 1212,
  [SMALL_STATE(84)] = 1216,
  [SMALL_STATE(85)] = 1220,
  [SMALL_STATE(86)] = 1224,
  [SMALL_STATE(87)] = 1228,
  [SMALL_STATE(88)] = 1232,
  [SMALL_STATE(89)] = 1236,
  [SMALL_STATE(90)] = 1240,
  [SMALL_STATE(91)] = 1244,
  [SMALL_STATE(92)] = 1248,
  [SMALL_STATE(93)] = 1252,
  [SMALL_STATE(94)] = 1256,
  [SMALL_STATE(95)] = 1260,
  [SMALL_STATE(96)] = 1264,
  [SMALL_STATE(97)] = 1268,
  [SMALL_STATE(98)] = 1272,
  [SMALL_STATE(99)] = 1276,
  [SMALL_STATE(100)] = 1280,
  [SMALL_STATE(101)] = 1284,
  [SMALL_STATE(102)] = 1288,
  [SMALL_STATE(103)] = 1292,
  [SMALL_STATE(104)] = 1296,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_array, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_array, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_item, 1, 0, 2),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_item, 1, 0, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_item, 3, 0, 3),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_item, 3, 0, 3),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_value, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_value, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scalar, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_object, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_object, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_array, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_array, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_paren, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_paren, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_double_paren, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_double_paren, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_array, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_array, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_paren, 1, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_paren, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_stripped, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_stripped, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_dparen, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_dparen, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_verbatim, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_verbatim, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_brace, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_brace, 2, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_object, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_object, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_close_bracket, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_close_bracket, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_stripped, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_stripped, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_verbatim, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_verbatim, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_object, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_object, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0),
  [232] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_key, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_key, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_pair, 4, 0, 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [277] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_stripped_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_stripped_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiline_stripped_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [299] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__marker_ws = 0,
  ts_external_token__strict_eol = 1,
  ts_external_token__stripped_close = 2,
  ts_external_token__verbatim_close = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__marker_ws] = sym__marker_ws,
  [ts_external_token__strict_eol] = sym__strict_eol,
  [ts_external_token__stripped_close] = sym__stripped_close,
  [ts_external_token__verbatim_close] = sym__verbatim_close,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__marker_ws] = true,
    [ts_external_token__strict_eol] = true,
    [ts_external_token__stripped_close] = true,
    [ts_external_token__verbatim_close] = true,
  },
  [2] = {
    [ts_external_token__verbatim_close] = true,
  },
  [3] = {
    [ts_external_token__stripped_close] = true,
  },
  [4] = {
    [ts_external_token__marker_ws] = true,
  },
  [5] = {
    [ts_external_token__strict_eol] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_ktav_external_scanner_create(void);
void tree_sitter_ktav_external_scanner_destroy(void *);
bool tree_sitter_ktav_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_ktav_external_scanner_serialize(void *, char *);
void tree_sitter_ktav_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ktav(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__key_segment,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_ktav_external_scanner_create,
      tree_sitter_ktav_external_scanner_destroy,
      tree_sitter_ktav_external_scanner_scan,
      tree_sitter_ktav_external_scanner_serialize,
      tree_sitter_ktav_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "ktav",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
