/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__key_segment = 1,
  sym__newline = 2,
  anon_sym_POUND = 3,
  aux_sym_comment_token1 = 4,
  sym_sep_raw = 5,
  sym_sep_int = 6,
  sym_sep_float = 7,
  sym_sep_string = 8,
  anon_sym_DOT = 9,
  anon_sym_LBRACE_RBRACE = 10,
  anon_sym_LBRACK_RBRACK = 11,
  anon_sym_LPAREN_RPAREN = 12,
  anon_sym_LPAREN_LPAREN_RPAREN_RPAREN = 13,
  sym__open_brace = 14,
  sym__close_brace = 15,
  sym__open_bracket = 16,
  sym__close_bracket = 17,
  sym__open_paren = 18,
  sym__close_paren = 19,
  sym__open_dparen = 20,
  sym__close_dparen = 21,
  sym_multiline_content_line = 22,
  sym__scalar_text = 23,
  sym_kw_null = 24,
  sym_kw_true = 25,
  sym_kw_false = 26,
  sym_source_file = 27,
  sym__line = 28,
  sym_blank_line = 29,
  sym_comment = 30,
  sym_object_pair = 31,
  sym_key = 32,
  sym_dotted_key = 33,
  sym__value_line = 34,
  sym_empty_value = 35,
  sym_empty_object = 36,
  sym_empty_array = 37,
  sym_empty_paren = 38,
  sym_empty_double_paren = 39,
  sym_compound_object = 40,
  sym_compound_array = 41,
  sym_array_item = 42,
  sym_multiline_stripped = 43,
  sym_multiline_verbatim = 44,
  sym_scalar = 45,
  sym_keyword = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_dotted_key_repeat1 = 48,
  aux_sym_compound_object_repeat1 = 49,
  aux_sym_compound_array_repeat1 = 50,
  aux_sym_multiline_stripped_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__key_segment] = "_key_segment",
  [sym__newline] = "_newline",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_sep_raw] = "sep_raw",
  [sym_sep_int] = "sep_int",
  [sym_sep_float] = "sep_float",
  [sym_sep_string] = "sep_string",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE_RBRACE] = "{}",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LPAREN_RPAREN] = "()",
  [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = "(())",
  [sym__open_brace] = "_open_brace",
  [sym__close_brace] = "_close_brace",
  [sym__open_bracket] = "_open_bracket",
  [sym__close_bracket] = "_close_bracket",
  [sym__open_paren] = "_open_paren",
  [sym__close_paren] = "_close_paren",
  [sym__open_dparen] = "_open_dparen",
  [sym__close_dparen] = "_close_dparen",
  [sym_multiline_content_line] = "multiline_content_line",
  [sym__scalar_text] = "_scalar_text",
  [sym_kw_null] = "kw_null",
  [sym_kw_true] = "kw_true",
  [sym_kw_false] = "kw_false",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_blank_line] = "blank_line",
  [sym_comment] = "comment",
  [sym_object_pair] = "object_pair",
  [sym_key] = "key",
  [sym_dotted_key] = "dotted_key",
  [sym__value_line] = "_value_line",
  [sym_empty_value] = "empty_value",
  [sym_empty_object] = "empty_object",
  [sym_empty_array] = "empty_array",
  [sym_empty_paren] = "empty_paren",
  [sym_empty_double_paren] = "empty_double_paren",
  [sym_compound_object] = "compound_object",
  [sym_compound_array] = "compound_array",
  [sym_array_item] = "array_item",
  [sym_multiline_stripped] = "multiline_stripped",
  [sym_multiline_verbatim] = "multiline_verbatim",
  [sym_scalar] = "scalar",
  [sym_keyword] = "keyword",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_dotted_key_repeat1] = "dotted_key_repeat1",
  [aux_sym_compound_object_repeat1] = "compound_object_repeat1",
  [aux_sym_compound_array_repeat1] = "compound_array_repeat1",
  [aux_sym_multiline_stripped_repeat1] = "multiline_stripped_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__key_segment] = sym__key_segment,
  [sym__newline] = sym__newline,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_sep_raw] = sym_sep_raw,
  [sym_sep_int] = sym_sep_int,
  [sym_sep_float] = sym_sep_float,
  [sym_sep_string] = sym_sep_string,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE_RBRACE] = anon_sym_LBRACE_RBRACE,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
  [sym__open_brace] = sym__open_brace,
  [sym__close_brace] = sym__close_brace,
  [sym__open_bracket] = sym__open_bracket,
  [sym__close_bracket] = sym__close_bracket,
  [sym__open_paren] = sym__open_paren,
  [sym__close_paren] = sym__close_paren,
  [sym__open_dparen] = sym__open_dparen,
  [sym__close_dparen] = sym__close_dparen,
  [sym_multiline_content_line] = sym_multiline_content_line,
  [sym__scalar_text] = sym__scalar_text,
  [sym_kw_null] = sym_kw_null,
  [sym_kw_true] = sym_kw_true,
  [sym_kw_false] = sym_kw_false,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_blank_line] = sym_blank_line,
  [sym_comment] = sym_comment,
  [sym_object_pair] = sym_object_pair,
  [sym_key] = sym_key,
  [sym_dotted_key] = sym_dotted_key,
  [sym__value_line] = sym__value_line,
  [sym_empty_value] = sym_empty_value,
  [sym_empty_object] = sym_empty_object,
  [sym_empty_array] = sym_empty_array,
  [sym_empty_paren] = sym_empty_paren,
  [sym_empty_double_paren] = sym_empty_double_paren,
  [sym_compound_object] = sym_compound_object,
  [sym_compound_array] = sym_compound_array,
  [sym_array_item] = sym_array_item,
  [sym_multiline_stripped] = sym_multiline_stripped,
  [sym_multiline_verbatim] = sym_multiline_verbatim,
  [sym_scalar] = sym_scalar,
  [sym_keyword] = sym_keyword,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_dotted_key_repeat1] = aux_sym_dotted_key_repeat1,
  [aux_sym_compound_object_repeat1] = aux_sym_compound_object_repeat1,
  [aux_sym_compound_array_repeat1] = aux_sym_compound_array_repeat1,
  [aux_sym_multiline_stripped_repeat1] = aux_sym_multiline_stripped_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__key_segment] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_sep_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_sep_int] = {
    .visible = true,
    .named = true,
  },
  [sym_sep_float] = {
    .visible = true,
    .named = true,
  },
  [sym_sep_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym__open_brace] = {
    .visible = false,
    .named = true,
  },
  [sym__close_brace] = {
    .visible = false,
    .named = true,
  },
  [sym__open_bracket] = {
    .visible = false,
    .named = true,
  },
  [sym__close_bracket] = {
    .visible = false,
    .named = true,
  },
  [sym__open_paren] = {
    .visible = false,
    .named = true,
  },
  [sym__close_paren] = {
    .visible = false,
    .named = true,
  },
  [sym__open_dparen] = {
    .visible = false,
    .named = true,
  },
  [sym__close_dparen] = {
    .visible = false,
    .named = true,
  },
  [sym_multiline_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar_text] = {
    .visible = false,
    .named = true,
  },
  [sym_kw_null] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_true] = {
    .visible = true,
    .named = true,
  },
  [sym_kw_false] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_object_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_key] = {
    .visible = true,
    .named = true,
  },
  [sym__value_line] = {
    .visible = false,
    .named = true,
  },
  [sym_empty_value] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_object] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_array] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_double_paren] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_object] = {
    .visible = true,
    .named = true,
  },
  [sym_compound_array] = {
    .visible = true,
    .named = true,
  },
  [sym_array_item] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_stripped] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_scalar] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_key_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_compound_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_stripped_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_marker = 2,
  field_separator = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_marker] = "marker",
  [field_separator] = "separator",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_separator, 1},
    {field_value, 2},
  [3] =
    {field_value, 0},
  [4] =
    {field_marker, 0},
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 23,
  [39] = 21,
  [40] = 22,
  [41] = 8,
  [42] = 24,
  [43] = 25,
  [44] = 26,
  [45] = 45,
  [46] = 11,
  [47] = 27,
  [48] = 16,
  [49] = 15,
  [50] = 50,
  [51] = 14,
  [52] = 9,
  [53] = 17,
  [54] = 18,
  [55] = 19,
  [56] = 12,
  [57] = 20,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 61,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 66,
  [68] = 64,
  [69] = 63,
  [70] = 65,
  [71] = 71,
  [72] = 71,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 79,
  [81] = 81,
  [82] = 77,
  [83] = 81,
  [84] = 76,
  [85] = 73,
  [86] = 75,
  [87] = 87,
  [88] = 74,
};

static const TSCharacterRange sym__key_segment_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '-'}, {'/', '9'}, {';', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '\n', 29,
        '\r', 1,
        '#', 30,
        '(', 39,
        '.', 38,
        ':', 37,
        '[', 7,
        ']', 10,
        'f', 42,
        'n', 51,
        't', 48,
        '{', 12,
        '\t', 2,
        ' ', 2,
        0x0b, 18,
        '\f', 18,
        '}', 18,
      );
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(29);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 29,
        '\r', 1,
        '#', 30,
        '(', 39,
        '.', 38,
        ':', 37,
        '[', 7,
        ']', 10,
        'f', 42,
        'n', 51,
        't', 48,
        '{', 12,
        '\t', 2,
        ' ', 2,
        0x0b, 18,
        '\f', 18,
        '}', 18,
      );
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 29,
        '\r', 1,
        '#', 31,
        '(', 71,
        ':', 76,
        '[', 66,
        ']', 68,
        'f', 77,
        'n', 86,
        't', 83,
        '{', 69,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(87);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 29,
        '\r', 1,
        '(', 71,
        '[', 66,
        'f', 77,
        'n', 86,
        't', 83,
        '{', 69,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(87);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(87);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(59);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(59);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(59);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(60);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '}') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(65);
      END_STATE();
    case 15:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead == ')') ADVANCE(26);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 18:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '\r') ADVANCE(14);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 20:
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == '\r') ADVANCE(19);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '\n') ADVANCE(61);
      END_STATE();
    case 22:
      if (lookahead == '\n') ADVANCE(63);
      END_STATE();
    case 23:
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 24:
      if (lookahead == '\n') ADVANCE(62);
      if (lookahead == '\r') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 25:
      if (lookahead == '\n') ADVANCE(64);
      END_STATE();
    case 26:
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == ':') ADVANCE(37);
      if (lookahead == '}') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(27);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{') ADVANCE(52);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_sep_raw);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_sep_int);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_sep_float);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_sep_string);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == '(') ADVANCE(41);
      if (lookahead == ')') ADVANCE(55);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == ')') ADVANCE(56);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == ')') ADVANCE(40);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'a') ADVANCE(45);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'e') ADVANCE(89);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'e') ADVANCE(90);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'l') ADVANCE(49);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'l') ADVANCE(88);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'l') ADVANCE(46);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'r') ADVANCE(50);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 's') ADVANCE(44);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'u') ADVANCE(43);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__key_segment);
      if (lookahead == 'u') ADVANCE(47);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__key_segment);
      if ((!eof && set_contains(sym__key_segment_character_set_1, 10, lookahead))) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE_RBRACE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_LPAREN_LPAREN_RPAREN_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__open_brace);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__close_brace);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__open_bracket);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__close_bracket);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__open_paren);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__close_paren);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__open_dparen);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__close_dparen);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_multiline_content_line);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(59);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ']') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(59);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '}') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(21);
      if (lookahead == '(') ADVANCE(73);
      if (lookahead == ')') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(22);
      if (lookahead == ')') ADVANCE(75);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == '\n') ADVANCE(63);
      if (lookahead == '\r') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0) ADVANCE(87);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == ')') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == ':') ADVANCE(34);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'a') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'e') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'l') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'l') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'l') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 's') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'u') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead == 'u') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__scalar_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_kw_null);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_kw_true);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_kw_false);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 27},
  [29] = {.lex_state = 27},
  [30] = {.lex_state = 27},
  [31] = {.lex_state = 27},
  [32] = {.lex_state = 27},
  [33] = {.lex_state = 27},
  [34] = {.lex_state = 27},
  [35] = {.lex_state = 27},
  [36] = {.lex_state = 27},
  [37] = {.lex_state = 27},
  [38] = {.lex_state = 27},
  [39] = {.lex_state = 27},
  [40] = {.lex_state = 27},
  [41] = {.lex_state = 27},
  [42] = {.lex_state = 27},
  [43] = {.lex_state = 27},
  [44] = {.lex_state = 27},
  [45] = {.lex_state = 27},
  [46] = {.lex_state = 27},
  [47] = {.lex_state = 27},
  [48] = {.lex_state = 27},
  [49] = {.lex_state = 27},
  [50] = {.lex_state = 27},
  [51] = {.lex_state = 27},
  [52] = {.lex_state = 27},
  [53] = {.lex_state = 27},
  [54] = {.lex_state = 27},
  [55] = {.lex_state = 27},
  [56] = {.lex_state = 27},
  [57] = {.lex_state = 27},
  [58] = {.lex_state = 27},
  [59] = {.lex_state = 27},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 16},
  [63] = {.lex_state = 15},
  [64] = {.lex_state = 15},
  [65] = {.lex_state = 15},
  [66] = {.lex_state = 16},
  [67] = {.lex_state = 16},
  [68] = {.lex_state = 16},
  [69] = {.lex_state = 15},
  [70] = {.lex_state = 15},
  [71] = {.lex_state = 32},
  [72] = {.lex_state = 32},
  [73] = {.lex_state = 27},
  [74] = {.lex_state = 27},
  [75] = {.lex_state = 27},
  [76] = {.lex_state = 27},
  [77] = {.lex_state = 27},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 27},
  [80] = {.lex_state = 27},
  [81] = {.lex_state = 27},
  [82] = {.lex_state = 27},
  [83] = {.lex_state = 27},
  [84] = {.lex_state = 27},
  [85] = {.lex_state = 27},
  [86] = {.lex_state = 27},
  [87] = {.lex_state = 27},
  [88] = {.lex_state = 27},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__key_segment] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_sep_raw] = ACTIONS(1),
    [sym_sep_int] = ACTIONS(1),
    [sym_sep_float] = ACTIONS(1),
    [sym_sep_string] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(1),
    [sym__open_brace] = ACTIONS(1),
    [sym__open_bracket] = ACTIONS(1),
    [sym__close_bracket] = ACTIONS(1),
    [sym_multiline_content_line] = ACTIONS(1),
    [sym_kw_null] = ACTIONS(1),
    [sym_kw_true] = ACTIONS(1),
    [sym_kw_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(78),
    [sym__line] = STATE(28),
    [sym_blank_line] = STATE(28),
    [sym_comment] = STATE(28),
    [sym_object_pair] = STATE(28),
    [sym_key] = STATE(58),
    [sym_dotted_key] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__key_segment] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_blank_line] = STATE(5),
    [sym_comment] = STATE(5),
    [sym__value_line] = STATE(10),
    [sym_empty_object] = STATE(10),
    [sym_empty_array] = STATE(10),
    [sym_empty_paren] = STATE(10),
    [sym_empty_double_paren] = STATE(10),
    [sym_compound_object] = STATE(10),
    [sym_compound_array] = STATE(10),
    [sym_array_item] = STATE(5),
    [sym_multiline_stripped] = STATE(10),
    [sym_multiline_verbatim] = STATE(10),
    [sym_scalar] = STATE(10),
    [sym_keyword] = STATE(10),
    [aux_sym_compound_array_repeat1] = STATE(5),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym__open_brace] = ACTIONS(25),
    [sym__open_bracket] = ACTIONS(27),
    [sym__close_bracket] = ACTIONS(29),
    [sym__open_paren] = ACTIONS(31),
    [sym__open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
  [STATE(3)] = {
    [sym_blank_line] = STATE(4),
    [sym_comment] = STATE(4),
    [sym__value_line] = STATE(10),
    [sym_empty_object] = STATE(10),
    [sym_empty_array] = STATE(10),
    [sym_empty_paren] = STATE(10),
    [sym_empty_double_paren] = STATE(10),
    [sym_compound_object] = STATE(10),
    [sym_compound_array] = STATE(10),
    [sym_array_item] = STATE(4),
    [sym_multiline_stripped] = STATE(10),
    [sym_multiline_verbatim] = STATE(10),
    [sym_scalar] = STATE(10),
    [sym_keyword] = STATE(10),
    [aux_sym_compound_array_repeat1] = STATE(4),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym__open_brace] = ACTIONS(25),
    [sym__open_bracket] = ACTIONS(27),
    [sym__close_bracket] = ACTIONS(39),
    [sym__open_paren] = ACTIONS(31),
    [sym__open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
  [STATE(4)] = {
    [sym_blank_line] = STATE(5),
    [sym_comment] = STATE(5),
    [sym__value_line] = STATE(10),
    [sym_empty_object] = STATE(10),
    [sym_empty_array] = STATE(10),
    [sym_empty_paren] = STATE(10),
    [sym_empty_double_paren] = STATE(10),
    [sym_compound_object] = STATE(10),
    [sym_compound_array] = STATE(10),
    [sym_array_item] = STATE(5),
    [sym_multiline_stripped] = STATE(10),
    [sym_multiline_verbatim] = STATE(10),
    [sym_scalar] = STATE(10),
    [sym_keyword] = STATE(10),
    [aux_sym_compound_array_repeat1] = STATE(5),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym__open_brace] = ACTIONS(25),
    [sym__open_bracket] = ACTIONS(27),
    [sym__close_bracket] = ACTIONS(41),
    [sym__open_paren] = ACTIONS(31),
    [sym__open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
  [STATE(5)] = {
    [sym_blank_line] = STATE(5),
    [sym_comment] = STATE(5),
    [sym__value_line] = STATE(10),
    [sym_empty_object] = STATE(10),
    [sym_empty_array] = STATE(10),
    [sym_empty_paren] = STATE(10),
    [sym_empty_double_paren] = STATE(10),
    [sym_compound_object] = STATE(10),
    [sym_compound_array] = STATE(10),
    [sym_array_item] = STATE(5),
    [sym_multiline_stripped] = STATE(10),
    [sym_multiline_verbatim] = STATE(10),
    [sym_scalar] = STATE(10),
    [sym_keyword] = STATE(10),
    [aux_sym_compound_array_repeat1] = STATE(5),
    [sym__newline] = ACTIONS(43),
    [anon_sym_POUND] = ACTIONS(46),
    [sym_sep_raw] = ACTIONS(49),
    [sym_sep_int] = ACTIONS(49),
    [sym_sep_float] = ACTIONS(49),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(52),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(55),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(58),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(61),
    [sym__open_brace] = ACTIONS(64),
    [sym__open_bracket] = ACTIONS(67),
    [sym__close_bracket] = ACTIONS(70),
    [sym__open_paren] = ACTIONS(72),
    [sym__open_dparen] = ACTIONS(75),
    [sym__scalar_text] = ACTIONS(78),
    [sym_kw_null] = ACTIONS(81),
    [sym_kw_true] = ACTIONS(81),
    [sym_kw_false] = ACTIONS(81),
  },
  [STATE(6)] = {
    [sym_blank_line] = STATE(2),
    [sym_comment] = STATE(2),
    [sym__value_line] = STATE(10),
    [sym_empty_object] = STATE(10),
    [sym_empty_array] = STATE(10),
    [sym_empty_paren] = STATE(10),
    [sym_empty_double_paren] = STATE(10),
    [sym_compound_object] = STATE(10),
    [sym_compound_array] = STATE(10),
    [sym_array_item] = STATE(2),
    [sym_multiline_stripped] = STATE(10),
    [sym_multiline_verbatim] = STATE(10),
    [sym_scalar] = STATE(10),
    [sym_keyword] = STATE(10),
    [aux_sym_compound_array_repeat1] = STATE(2),
    [sym__newline] = ACTIONS(11),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_sep_raw] = ACTIONS(15),
    [sym_sep_int] = ACTIONS(15),
    [sym_sep_float] = ACTIONS(15),
    [anon_sym_LBRACE_RBRACE] = ACTIONS(17),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(19),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_LPAREN_LPAREN_RPAREN_RPAREN] = ACTIONS(23),
    [sym__open_brace] = ACTIONS(25),
    [sym__open_bracket] = ACTIONS(27),
    [sym__close_bracket] = ACTIONS(84),
    [sym__open_paren] = ACTIONS(31),
    [sym__open_dparen] = ACTIONS(33),
    [sym__scalar_text] = ACTIONS(35),
    [sym_kw_null] = ACTIONS(37),
    [sym_kw_true] = ACTIONS(37),
    [sym_kw_false] = ACTIONS(37),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(86), 1,
      sym__newline,
    ACTIONS(88), 1,
      anon_sym_LBRACE_RBRACE,
    ACTIONS(90), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(92), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(94), 1,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
    ACTIONS(96), 1,
      sym__open_brace,
    ACTIONS(98), 1,
      sym__open_bracket,
    ACTIONS(100), 1,
      sym__open_paren,
    ACTIONS(102), 1,
      sym__open_dparen,
    ACTIONS(104), 1,
      sym__scalar_text,
    ACTIONS(106), 3,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
    STATE(50), 12,
      sym__value_line,
      sym_empty_value,
      sym_empty_object,
      sym_empty_array,
      sym_empty_paren,
      sym_empty_double_paren,
      sym_compound_object,
      sym_compound_array,
      sym_multiline_stripped,
      sym_multiline_verbatim,
      sym_scalar,
      sym_keyword,
  [50] = 2,
    ACTIONS(110), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(108), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [73] = 2,
    ACTIONS(114), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(112), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [96] = 2,
    ACTIONS(118), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(116), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [119] = 2,
    ACTIONS(122), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(120), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [142] = 2,
    ACTIONS(126), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(124), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [165] = 2,
    ACTIONS(130), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(128), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [188] = 2,
    ACTIONS(134), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(132), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [211] = 2,
    ACTIONS(138), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(136), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [234] = 2,
    ACTIONS(142), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(140), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [257] = 2,
    ACTIONS(146), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(144), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [280] = 2,
    ACTIONS(150), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(148), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [303] = 2,
    ACTIONS(154), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(152), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [326] = 2,
    ACTIONS(158), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(156), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [349] = 2,
    ACTIONS(162), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(160), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [372] = 2,
    ACTIONS(166), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(164), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [395] = 2,
    ACTIONS(170), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(168), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [418] = 2,
    ACTIONS(174), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(172), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [441] = 2,
    ACTIONS(178), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(176), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [464] = 2,
    ACTIONS(182), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(180), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [487] = 2,
    ACTIONS(186), 2,
      anon_sym_POUND,
      sym__scalar_text,
    ACTIONS(184), 16,
      sym__newline,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_LBRACE_RBRACE,
      anon_sym_LBRACK_RBRACK,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LPAREN_LPAREN_RPAREN_RPAREN,
      sym__open_brace,
      sym__open_bracket,
      sym__close_bracket,
      sym__open_paren,
      sym__open_dparen,
      sym_kw_null,
      sym_kw_true,
      sym_kw_false,
  [510] = 7,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    STATE(58), 1,
      sym_key,
    STATE(59), 1,
      sym_dotted_key,
    STATE(29), 5,
      sym__line,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_source_file_repeat1,
  [536] = 7,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
    ACTIONS(192), 1,
      sym__key_segment,
    ACTIONS(195), 1,
      sym__newline,
    ACTIONS(198), 1,
      anon_sym_POUND,
    STATE(58), 1,
      sym_key,
    STATE(59), 1,
      sym_dotted_key,
    STATE(29), 5,
      sym__line,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_source_file_repeat1,
  [562] = 7,
    ACTIONS(201), 1,
      sym__key_segment,
    ACTIONS(204), 1,
      sym__newline,
    ACTIONS(207), 1,
      anon_sym_POUND,
    ACTIONS(210), 1,
      sym__close_brace,
    STATE(58), 1,
      sym_key,
    STATE(59), 1,
      sym_dotted_key,
    STATE(30), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [587] = 7,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(212), 1,
      sym__close_brace,
    STATE(58), 1,
      sym_key,
    STATE(59), 1,
      sym_dotted_key,
    STATE(34), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [612] = 7,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(214), 1,
      sym__close_brace,
    STATE(58), 1,
      sym_key,
    STATE(59), 1,
      sym_dotted_key,
    STATE(33), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [637] = 7,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(216), 1,
      sym__close_brace,
    STATE(58), 1,
      sym_key,
    STATE(59), 1,
      sym_dotted_key,
    STATE(30), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [662] = 7,
    ACTIONS(5), 1,
      sym__key_segment,
    ACTIONS(7), 1,
      sym__newline,
    ACTIONS(9), 1,
      anon_sym_POUND,
    ACTIONS(218), 1,
      sym__close_brace,
    STATE(58), 1,
      sym_key,
    STATE(59), 1,
      sym_dotted_key,
    STATE(30), 4,
      sym_blank_line,
      sym_comment,
      sym_object_pair,
      aux_sym_compound_object_repeat1,
  [687] = 4,
    ACTIONS(222), 1,
      sym_sep_string,
    ACTIONS(224), 1,
      anon_sym_DOT,
    STATE(35), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(220), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [702] = 4,
    ACTIONS(229), 1,
      sym_sep_string,
    ACTIONS(231), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(227), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [717] = 4,
    ACTIONS(231), 1,
      anon_sym_DOT,
    ACTIONS(235), 1,
      sym_sep_string,
    STATE(35), 1,
      aux_sym_dotted_key_repeat1,
    ACTIONS(233), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [732] = 1,
    ACTIONS(168), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [740] = 1,
    ACTIONS(160), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [748] = 1,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [756] = 1,
    ACTIONS(108), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [764] = 1,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [772] = 1,
    ACTIONS(176), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [780] = 1,
    ACTIONS(180), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [788] = 2,
    ACTIONS(222), 1,
      sym_sep_string,
    ACTIONS(220), 4,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
      anon_sym_DOT,
  [798] = 1,
    ACTIONS(120), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [806] = 1,
    ACTIONS(184), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [814] = 1,
    ACTIONS(140), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [822] = 1,
    ACTIONS(136), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [830] = 1,
    ACTIONS(237), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [838] = 1,
    ACTIONS(132), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [846] = 1,
    ACTIONS(112), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [854] = 1,
    ACTIONS(144), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [862] = 1,
    ACTIONS(148), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [870] = 1,
    ACTIONS(152), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [878] = 1,
    ACTIONS(124), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [886] = 1,
    ACTIONS(156), 5,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_POUND,
      sym__key_segment,
      sym__close_brace,
  [894] = 2,
    ACTIONS(241), 1,
      sym_sep_string,
    ACTIONS(239), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [903] = 2,
    ACTIONS(229), 1,
      sym_sep_string,
    ACTIONS(227), 3,
      sym_sep_raw,
      sym_sep_int,
      sym_sep_float,
  [912] = 3,
    ACTIONS(243), 1,
      sym__newline,
    ACTIONS(245), 1,
      sym__scalar_text,
    STATE(13), 2,
      sym_empty_value,
      sym_scalar,
  [923] = 3,
    ACTIONS(247), 1,
      sym__close_paren,
    ACTIONS(249), 1,
      sym_multiline_content_line,
    STATE(67), 1,
      aux_sym_multiline_stripped_repeat1,
  [933] = 3,
    ACTIONS(251), 1,
      sym__close_paren,
    ACTIONS(253), 1,
      sym_multiline_content_line,
    STATE(66), 1,
      aux_sym_multiline_stripped_repeat1,
  [943] = 3,
    ACTIONS(255), 1,
      sym__close_dparen,
    ACTIONS(257), 1,
      sym_multiline_content_line,
    STATE(65), 1,
      aux_sym_multiline_stripped_repeat1,
  [953] = 3,
    ACTIONS(259), 1,
      sym__close_dparen,
    ACTIONS(261), 1,
      sym_multiline_content_line,
    STATE(64), 1,
      aux_sym_multiline_stripped_repeat1,
  [963] = 3,
    ACTIONS(264), 1,
      sym__close_dparen,
    ACTIONS(266), 1,
      sym_multiline_content_line,
    STATE(64), 1,
      aux_sym_multiline_stripped_repeat1,
  [973] = 3,
    ACTIONS(268), 1,
      sym__close_paren,
    ACTIONS(270), 1,
      sym_multiline_content_line,
    STATE(68), 1,
      aux_sym_multiline_stripped_repeat1,
  [983] = 3,
    ACTIONS(270), 1,
      sym_multiline_content_line,
    ACTIONS(272), 1,
      sym__close_paren,
    STATE(68), 1,
      aux_sym_multiline_stripped_repeat1,
  [993] = 3,
    ACTIONS(259), 1,
      sym__close_paren,
    ACTIONS(274), 1,
      sym_multiline_content_line,
    STATE(68), 1,
      aux_sym_multiline_stripped_repeat1,
  [1003] = 3,
    ACTIONS(277), 1,
      sym__close_dparen,
    ACTIONS(279), 1,
      sym_multiline_content_line,
    STATE(70), 1,
      aux_sym_multiline_stripped_repeat1,
  [1013] = 3,
    ACTIONS(266), 1,
      sym_multiline_content_line,
    ACTIONS(281), 1,
      sym__close_dparen,
    STATE(64), 1,
      aux_sym_multiline_stripped_repeat1,
  [1023] = 2,
    ACTIONS(283), 1,
      sym__newline,
    ACTIONS(285), 1,
      aux_sym_comment_token1,
  [1030] = 2,
    ACTIONS(287), 1,
      sym__newline,
    ACTIONS(289), 1,
      aux_sym_comment_token1,
  [1037] = 1,
    ACTIONS(291), 1,
      sym__newline,
  [1041] = 1,
    ACTIONS(293), 1,
      sym__newline,
  [1045] = 1,
    ACTIONS(295), 1,
      sym__newline,
  [1049] = 1,
    ACTIONS(297), 1,
      sym__newline,
  [1053] = 1,
    ACTIONS(299), 1,
      sym__newline,
  [1057] = 1,
    ACTIONS(301), 1,
      ts_builtin_sym_end,
  [1061] = 1,
    ACTIONS(303), 1,
      sym__newline,
  [1065] = 1,
    ACTIONS(305), 1,
      sym__newline,
  [1069] = 1,
    ACTIONS(307), 1,
      sym__newline,
  [1073] = 1,
    ACTIONS(309), 1,
      sym__newline,
  [1077] = 1,
    ACTIONS(311), 1,
      sym__newline,
  [1081] = 1,
    ACTIONS(313), 1,
      sym__newline,
  [1085] = 1,
    ACTIONS(315), 1,
      sym__newline,
  [1089] = 1,
    ACTIONS(317), 1,
      sym__newline,
  [1093] = 1,
    ACTIONS(319), 1,
      sym__key_segment,
  [1097] = 1,
    ACTIONS(321), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 73,
  [SMALL_STATE(10)] = 96,
  [SMALL_STATE(11)] = 119,
  [SMALL_STATE(12)] = 142,
  [SMALL_STATE(13)] = 165,
  [SMALL_STATE(14)] = 188,
  [SMALL_STATE(15)] = 211,
  [SMALL_STATE(16)] = 234,
  [SMALL_STATE(17)] = 257,
  [SMALL_STATE(18)] = 280,
  [SMALL_STATE(19)] = 303,
  [SMALL_STATE(20)] = 326,
  [SMALL_STATE(21)] = 349,
  [SMALL_STATE(22)] = 372,
  [SMALL_STATE(23)] = 395,
  [SMALL_STATE(24)] = 418,
  [SMALL_STATE(25)] = 441,
  [SMALL_STATE(26)] = 464,
  [SMALL_STATE(27)] = 487,
  [SMALL_STATE(28)] = 510,
  [SMALL_STATE(29)] = 536,
  [SMALL_STATE(30)] = 562,
  [SMALL_STATE(31)] = 587,
  [SMALL_STATE(32)] = 612,
  [SMALL_STATE(33)] = 637,
  [SMALL_STATE(34)] = 662,
  [SMALL_STATE(35)] = 687,
  [SMALL_STATE(36)] = 702,
  [SMALL_STATE(37)] = 717,
  [SMALL_STATE(38)] = 732,
  [SMALL_STATE(39)] = 740,
  [SMALL_STATE(40)] = 748,
  [SMALL_STATE(41)] = 756,
  [SMALL_STATE(42)] = 764,
  [SMALL_STATE(43)] = 772,
  [SMALL_STATE(44)] = 780,
  [SMALL_STATE(45)] = 788,
  [SMALL_STATE(46)] = 798,
  [SMALL_STATE(47)] = 806,
  [SMALL_STATE(48)] = 814,
  [SMALL_STATE(49)] = 822,
  [SMALL_STATE(50)] = 830,
  [SMALL_STATE(51)] = 838,
  [SMALL_STATE(52)] = 846,
  [SMALL_STATE(53)] = 854,
  [SMALL_STATE(54)] = 862,
  [SMALL_STATE(55)] = 870,
  [SMALL_STATE(56)] = 878,
  [SMALL_STATE(57)] = 886,
  [SMALL_STATE(58)] = 894,
  [SMALL_STATE(59)] = 903,
  [SMALL_STATE(60)] = 912,
  [SMALL_STATE(61)] = 923,
  [SMALL_STATE(62)] = 933,
  [SMALL_STATE(63)] = 943,
  [SMALL_STATE(64)] = 953,
  [SMALL_STATE(65)] = 963,
  [SMALL_STATE(66)] = 973,
  [SMALL_STATE(67)] = 983,
  [SMALL_STATE(68)] = 993,
  [SMALL_STATE(69)] = 1003,
  [SMALL_STATE(70)] = 1013,
  [SMALL_STATE(71)] = 1023,
  [SMALL_STATE(72)] = 1030,
  [SMALL_STATE(73)] = 1037,
  [SMALL_STATE(74)] = 1041,
  [SMALL_STATE(75)] = 1045,
  [SMALL_STATE(76)] = 1049,
  [SMALL_STATE(77)] = 1053,
  [SMALL_STATE(78)] = 1057,
  [SMALL_STATE(79)] = 1061,
  [SMALL_STATE(80)] = 1065,
  [SMALL_STATE(81)] = 1069,
  [SMALL_STATE(82)] = 1073,
  [SMALL_STATE(83)] = 1077,
  [SMALL_STATE(84)] = 1081,
  [SMALL_STATE(85)] = 1085,
  [SMALL_STATE(86)] = 1089,
  [SMALL_STATE(87)] = 1093,
  [SMALL_STATE(88)] = 1097,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_array_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scalar, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scalar, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_array, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_array, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_item, 1, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_item, 1, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_item, 2, 0, 3),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_item, 2, 0, 3),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_object, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_object, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_value, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_value, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_paren, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_paren, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_empty_double_paren, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_empty_double_paren, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_object, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_object, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_array, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_array, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_stripped, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_stripped, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_verbatim, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_verbatim, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_stripped, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_stripped, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_object, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_object, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound_array, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound_array, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_verbatim, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_multiline_verbatim, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_compound_object_repeat1, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_key_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_key, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_key, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dotted_key, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_pair, 3, 0, 1),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiline_stripped_repeat1, 2, 0, 0),
  [261] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multiline_stripped_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [274] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multiline_stripped_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [301] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ktav(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym__key_segment,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
